### PR TITLE
make versioncheck more robust

### LINKED ISSUE #132: Doesn't recognize Opera for Android as a capable browser
I just reported this to Opera (bug DNA-43013), the problem is that `window.chrome` is not defined like in desktop version.

Don't know if we can do something here to be able to recognize this like user agent detection.

### LINKED ISSUE #135: Requests from Chrome WebView no longer detected as Chrome
5c5fff7b8972a0871a2f023fcc00c34eb2605834 changed the Chrome detection logic from:

``` javascript
else if (navigator.webkitGetUserMedia)
```

to:

``` javascript
else if (navigator.webkitGetUserMedia && !!window.chrome)
```

Unfortunately, window.chrome is not present for WebView. This is mentioned in [this Chromium bug report](https://code.google.com/p/chromium/issues/detail?id=527483#c19), but I think it's view restricted, so here's the relevant text:

> is it expected that !!window.chrome returns false for WebView?
> Checked webview m39 and trunk. Nope, window.chrome is not there for webview.

I'm hoping that reverting just that part of 5c5fff7b8972a0871a2f023fcc00c34eb2605834 is enough to make WebView requests be detected as Chrome again, but I'm not certain.

Instructions to build WebView, and in particular the WebView shell app, are available [here](https://www.chromium.org/developers/how-tos/android-build-instructions#TOC-Build-WebView-shell).

### PR DESCRIPTION
**Pull request by fippo**
This fixes #132 and #122
@tednakamura can you check http://hancke.name/tmp/opr.html shows a version instead of a blank page in webview? (it would then fix #135)

Not sure what the unsupported version should be... set it to 0.

### CODE REVIEW

File: adapter.js [hunk 1]
```diff
@@ -227,14 +227,18 @@ if (typeof window === 'undefined' || !window.navigator) {
       });
     };
   }
-} else if (navigator.webkitGetUserMedia && !!window.chrome) {
+} else if (navigator.webkitGetUserMedia && window.webkitRTCPeerConnection) {
   webrtcUtils.log('This appears to be Chrome');
```
Comment (alvestrand) [inline adapter.js:235]: Please continue checking window.chrome. There is at least one other Webkit-based browser out there with WebRTC functionality (Bowser).
(Note: opera has defined window.chrome, but does not define webkitRTCPeerConnection - it is instead defined on window.)

File: adapter.js [hunk 2]
```diff
@@ -227,14 +227,18 @@ if (typeof window === 'undefined' || !window.navigator) {
...
 
   webrtcDetectedBrowser = 'chrome';
 
   // the detected chrome version.
-  webrtcDetectedVersion =
-    parseInt(navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)[2], 10);
+  webrtcDetectedVersion = navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);
```
Comment (alvestrand) [inline adapter.js]: Please use a different (local) temporary variable. Overwriting a string with an integer is just ugly.

**Comment by alvestrand** [comment]
Can you write a test for this? (asking, not requesting - it would probably involve extending pretendVersion to take strings).

File: adapter.js (hunk 2 above)
Comment (fippo) [inline adapter.js]: function scope hence global scope. The solution turned out not to be that bad... done.

I am looking forward to using browserify to generate adapter so we can declare all the variables we like :-)

File: adapter.js (hunk 1 above)
Comment (fippo) [inline adapter.js:235]: but we want to work in a webview (see #135) where window.chrome is not defined.

Bowser does not use webkitGetUserMedia and webkitRTCPeerConnection hopefully. Checking for window.webkitRTCPeerConnection seems mandatory to me since we later fiddle with it.

**Comment by fippo** [comment]
A test for webrtcUtils.extractionVersionFromUserAgent that throws some matching and non matching strings into it and makes sure things don't blow up like they did in the past?

**Comment by tednakamura** [comment]
http://hancke.name/tmp/opr.html lgtm - see attached screenshot:
webview-good

And as a comparison, here's what happens when I visit https://webrtc.github.io/samples/src/content/getusermedia/gum/ with the same webview instance:
webview-bad

**Comment by fippo** [comment]
@tednakamura: thanks, that is what I was hoping for.

testing turns out to be more complicated since
- navigator.userAgent can't be fiddled with
- I don't want add another global variable while we're in non-module module
- putting it onto webrtcUtils along with log() seemed ok but that is not exported to the module (which is good imo)

**Comment by alvestrand** [comment]
@fippo would it work to put the parsing code (parseUserAgent?) into webrtcUtils, call webrtcUtils.parseUserAgent() from the tests, and call webrtcUtils.parseUserAgent(navigator.userAgent) in the main execution thread?

**Comment by pavlospt** [comment]
Does anyone know when this will be merged?

**Comment by fippo** [comment]
@alvestrand ugly but works. done.
Also made the two other version checks use this. The match position argument is somewhat odd since it relies on the user to know about the semantics of match but... that's safe to assume when passing a regexp before that argument.

**Comment by fippo** [comment]
right, but that way leads to reinventing browser version detection modules -- which is why I'd rather keep this as a "safe regexp"

**Comment by KaptenJansson** [comment]
Anything else needed here?

**Comment by calebboyd** [comment]
It looks like the chrome specific patches will be applied in a shimmed safari environment (on iOS). I don't know if this would have any negative side effects but I should be able to test it soon.

**Comment by fippo** [comment]
@calebboyd does that env have webkitRTCPeerConnection?

**Comment by calebboyd** [comment]
Yeah, here is the specific shim I'm referring to [eface2face/iosrtc](https://github.com/eface2face/cordova-plugin-iosrtc/blob/master/docs/iosrtc.md#iosrtcregisterglobals)

I could also just delete it after it is written so it will fall through...

**Comment by fippo** [comment]
i'd suggest that this code doesn't attempt to register chrome-specific prefixed objects (which webkitRTCPeerConnection is despite the name). Ideally adapter would check for !window.RTCPeerConnection also, but the code will need to be more modular for that.

**Comment by alvestrand** [comment]
This part is done. I've merged it.

**Comment by calebboyd** [comment]
Was just able to test this on iOS and it is no longer working. I'll see if I can come up with a patch...

For now I can just `delete window.webkitRTCPeerConnection` after `iosrtc.registerGlobals` is called

**Comment by tgabi333** [comment]
What if you provide a way to force a behavior and skip detection?

**Comment by leonklingele** [comment]
:+1:
