### PR TITLE
Shim parameterless SLD in Safari

### LINKED ISSUE #1084: RTCPeerConnection.setLocalDescription() without arguments fails on Safari 13.1 (macOS Catalina 10.15.4) with TypeError: Argument 1 ('description') to RTCPeerConnection.setLocalDescription must be an instance of RTCSessionDescription
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used (**kinda, see below**)

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Safari Version 13.1 (15609.1.20.111.8)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15

**adapter.js (e.g. 6.1.0)**
8.0.0

## Description
Calling `RTCPeerConnection.setLocalDescription()` without any arguments in Safari 13.1 (macOS Catalina 10.15.4) fails with:
> TypeError: Argument 1 ('description') to RTCPeerConnection.setLocalDescription must be an instance of RTCSessionDescription

## Steps to reproduce
https://jsfiddle.net/60ne23pb/1/
```javascript
const ctx = new (window.AudioContext || webkitAudioContext)();
const gain = ctx.createGain();
const {stream} = gain.connect(ctx.createMediaStreamDestination());
const track = stream.getAudioTracks()[0];

const pc = new RTCPeerConnection({});
pc.addEventListener('negotiationneeded', async () => {
  await pc.setLocalDescription();
});
pc.addTrack(track, stream);
```

## Expected results
It should behave according to [the spec](https://www.w3.org/TR/2021/REC-webrtc-20210126/#dom-peerconnection-setlocaldescription):

> Passing in a description is optional. If left out, then setLocalDescription will implicitly create an offer or create an answer, as needed.

## Actual results
Throws the following exception:
> TypeError: Argument 1 ('description') to RTCPeerConnection.setLocalDescription must be an instance of RTCSessionDescription

Removing adapter.js changes the behavior slightly; it instead throws:
> TypeError: Not enough arguments

### PR DESCRIPTION
**Pull request by jan-ivar**
Fixes https://github.com/webrtcHacks/adapter/issues/1084. Disclaimer: I haven't built it, as I don't have my npm setup for this atm.

### CODE REVIEW

File: src/js/safari/safari_shim.js [hunk 1]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+  if (!(window.RTCPeerConnection && window.RTCPeerConnection.prototype)) {
+    return;
+  }
+  const nativeSetLocalDescription =
+      window.RTCPeerConnection.prototype.setLocalDescription;
+  if (!nativeSetLocalDescription || nativeSetLocalDescription.length === 0) {
+    return;
+  }
+  window.RTCPeerConnection.prototype.setLocalDescription =
+    function setLocalDescription() {
```
Comment (rhansen) [inline src/js/safari/safari_shim.js:365]: Is it necessary to support the case where `desc` is non-null but `desc.type` is falsy? If not, I think the function can be simplified:

```javascript
  window.RTCPeerConnection.prototype.setLocalDescription = async function (...args) {
    if (args.length === 0) {
      // The description should technically be created when the SLD comes off
      // the RTCPeerConnection's operations chain (not ahead of going on it),
      // but this is too difficult to shim. Instead, this shim only covers the
      // common case where the operations chain is empty. This is imperfect, but
      // should cover many cases. Rationale: Even if we can't reduce the glare
      // window to zero on imperfect implementations, there's value in tapping
      // into the perfect negotiation pattern that several browsers support.
      const createOffer =
          ['stable', 'have-local-offer', 'have-remote-pranswer'].includes(this.signalingState);
      args.push(createOffer ? await this.createOffer() : await this.createAnswer());
    }
    return await nativeSetLocalDescription.call(this, ...args);
  };
```

File: src/js/safari/safari_shim.js [hunk 2]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+// Note: Make sure to call this ahead of shimCallbacksAPI.
+export function shimParameterlessSetLocalDescription(window, browserDetails) {
+  if (!(window.RTCPeerConnection && window.RTCPeerConnection.prototype)) {
+    return;
+  }
+  const nativeSetLocalDescription =
+      window.RTCPeerConnection.prototype.setLocalDescription;
+  if (!nativeSetLocalDescription || nativeSetLocalDescription.length === 0) {
+    return;
+  }
```
Comment (rhansen) [inline src/js/safari/safari_shim.js:363]: Would the following be a more robust way to feature test? I think this will work even if `shimParameterlessSetLocalDescription()` is called after `shimCallbacksAPI()`. Unfortunately, it is asynchronous, which might be a dealbreaker.

```javascript
  const nativeSetLocalDescription =
      window.RTCPeerConnection &&
      window.RTCPeerConnection.prototype &&
      window.RTCPeerConnection.prototype.setLocalDescription;
  if (!nativeSetLocalDescription) return;
  try {
    await new window.RTCPeerConnection().setLocalDescription();
    return;
  } catch (err) {}
```

File: src/js/safari/safari_shim.js [hunk 3]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+            desc.type = "answer";
+            break;
+        }
+      }
+      if (desc.sdp) {
+        return nativeSetLocalDescription.apply(this, [desc]);
+      }
+      const func = desc.type == "offer" ? this.createOffer : this.createAnswer;
+      return func.apply(this)
+        .then(desc => nativeSetLocalDescription.apply(this, [desc]);
```
Comment (rhansen) [inline src/js/safari/safari_shim.js]: Missing closing paren:
```suggestion
        .then(desc => nativeSetLocalDescription.apply(this, [desc]));
```

**Review by rhansen — COMMENTED** [review]
Thank you for this!

**Comment by rhansen** [comment]
After adding the missing parenthesis it works as expected.

File: src/js/safari/safari_shim.js (hunk 2 above)
Comment (fippo) [reply src/js/safari/safari_shim.js:363]: i'm not a fan of creating peerconnections and disposing them for the sake of feature deteection.
Observing the order or pulling the "need to" check before doing any modifications should be fine.

File: src/js/safari/safari_shim.js [hunk 4]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+  }
+  const nativeSetLocalDescription =
+      window.RTCPeerConnection.prototype.setLocalDescription;
+  if (!nativeSetLocalDescription || nativeSetLocalDescription.length === 0) {
+    return;
+  }
+  window.RTCPeerConnection.prototype.setLocalDescription =
+    function setLocalDescription() {
+      let desc = arguments[0] || {};
+      if (typeof desc != "object" || (desc.type && desc.sdp)) {
```
Comment (fippo) [inline src/js/safari/safari_shim.js:367]: !==

Comment (fippo) [inline src/js/safari/safari_shim.js]:
```suggestion
      if (typeof desc !== "object" || (desc.type && desc.sdp)) {
```
needs extra check for rollback?

File: src/js/safari/safari_shim.js (hunk 1 above)
Comment (jan-ivar) [reply src/js/safari/safari_shim.js:365]: Polyfills run ahead of WebIDL's input validation or normalization. WebIDL says all these must work equivalently:
```js
await pc.setLocalDescription();
await pc.setLocalDescription(null);
await pc.setLocalDescription({});
await pc.setLocalDescription({foo: 3});
```
Also, the way the [spec](https://w3c.github.io/webrtc-pc/#dom-peerconnection-setlocaldescription) is written (and [implemented in firefox](https://searchfox.org/mozilla-central/rev/4163c8f09b03871e053a61f39de020fa09e02ea9/dom/media/PeerConnection.jsm#1071,1083)), the dynamic defaults for `type` and `sdp` are provided independently, which means the following combinations should also work (or fail predictably depending on state):
```js
await pc.setLocalDescription({type: "offer"});
await pc.setLocalDescription({type: "answer"});
await pc.setLocalDescription({sdp: sdp});
```

As a backwards-compatible shim, Adapter also avoids `async`/`await`, since they don't parse on older browsers.

File: src/js/safari/safari_shim.js (hunk 4 above)
Comment (jan-ivar) [reply src/js/safari/safari_shim.js]: Good catch on `"rollback"`!

I'll yield to the prevailing pattern in this module on !== and ===

File: src/js/safari/safari_shim.js [hunk 5]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+          case "have-local-offer":
+          case "have-remote-pranswer":
+            desc.type = "offer";
+            break;
+          default:
+            desc.type = "answer";
+            break;
+        }
+      }
+      if (desc.sdp) {
```
Comment (jan-ivar) [inline src/js/safari/safari_shim.js]:
```suggestion
      if (desc.sdp || (desc.type != "offer" && desc.type != "answer")) {
```

File: src/js/safari/safari_shim.js [hunk 6]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+            break;
+          default:
+            desc.type = "answer";
+            break;
+        }
+      }
+      if (desc.sdp || (desc.type != "offer" && desc.type != "answer")) {
+        return nativeSetLocalDescription.apply(this, [desc]);
+      }
+      const func = desc.type == "offer" ? this.createOffer : this.createAnswer;
```
Comment (jan-ivar) [inline src/js/safari/safari_shim.js]:
```suggestion
          case 'stable':
          case 'have-local-offer':
          case 'have-remote-pranswer':
            desc.type = 'offer';
            break;
          default:
            desc.type = 'answer';
            break;
        }
      }
      if (desc.sdp || (desc.type != 'offer' && desc.type != 'answer')) {
        return nativeSetLocalDescription.apply(this, [desc]);
      }
      const func = desc.type == 'offer' ? this.createOffer : this.createAnswer;
```

File: src/js/safari/safari_shim.js [hunk 7]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+  }
+  const nativeSetLocalDescription =
+      window.RTCPeerConnection.prototype.setLocalDescription;
+  if (!nativeSetLocalDescription || nativeSetLocalDescription.length === 0) {
+    return;
+  }
+  window.RTCPeerConnection.prototype.setLocalDescription =
+    function setLocalDescription() {
+      let desc = arguments[0] || {};
+      if (typeof desc !== "object" || (desc.type && desc.sdp)) {
```
Comment (jan-ivar) [inline src/js/safari/safari_shim.js]:
```suggestion
      if (typeof desc !== 'object' || (desc.type && desc.sdp)) {
```

File: src/js/safari/safari_shim.js [hunk 8]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+          case 'have-local-offer':
+          case 'have-remote-pranswer':
+            desc.type = 'offer';
+            break;
+          default:
+            desc.type = 'answer';
+            break;
+        }
+      }
+      if (desc.sdp || (desc.type != 'offer' && desc.type != 'answer')) {
```
Comment (jan-ivar) [inline src/js/safari/safari_shim.js]:
```suggestion
      if (desc.sdp || (desc.type !== 'offer' && desc.type !== 'answer')) {
```

File: src/js/safari/safari_shim.js [hunk 9]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+        return nativeSetLocalDescription.apply(this, [desc]);
+      }
+      const func = desc.type == 'offer' ? this.createOffer : this.createAnswer;
```
Comment (jan-ivar) [inline src/js/safari/safari_shim.js]:
```suggestion
      const func = desc.type === 'offer' ? this.createOffer : this.createAnswer;
```

File: src/js/safari/safari_shim.js [hunk 10]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+      return func.apply(this)
+        .then(desc => nativeSetLocalDescription.apply(this, [desc]));
```
Comment (jan-ivar) [inline src/js/safari/safari_shim.js]:
```suggestion
        .then(description => nativeSetLocalDescription.apply(this, [description]));
```

File: src/js/safari/safari_shim.js [hunk 11]
```diff
@@ -350,3 +350,48 @@ export function shimAudioContext(window) {
...
+            desc.type = 'answer';
+            break;
+        }
+      }
+      if (desc.sdp || (desc.type !== 'offer' && desc.type !== 'answer')) {
+        return nativeSetLocalDescription.apply(this, [desc]);
+      }
+      const func = desc.type === 'offer' ? this.createOffer : this.createAnswer;
+      return func.apply(this)
+        .then(description => nativeSetLocalDescription.apply(this, [description]));
```
Comment (jan-ivar) [inline src/js/safari/safari_shim.js]:
```suggestion
        .then(d => nativeSetLocalDescription.apply(this, [d]));
```

**Review by fippo — APPROVED** [review]

**Comment by rhansen** [comment]
I just tested the latest version and it still works well. Thank you!

**Comment by rhansen** [comment]
I encountered an old Chrome that also lacks support for parameterless SLD. Can this be added to Chrome as well? Moving `shimParameterlessSetLocalDescription()` to `common_shim.js` and calling it for Chrome seems to work just fine in my limited testing.

**Comment by fippo** [comment]
so Firefox added this in FF75 (https://bugzilla.mozilla.org/show_bug.cgi?id=1568292)
@henbos can you check what Chrome version this shipped in?

Given that is using proper feature detection moving it to the common shim seems like a good idea. This might be a bit trickier due to more things manipulating setLocalDescription though.

**Comment by fippo** [comment]
i'll do the chrome/firefox bits (which is somewhat ironic since jib knows firefox better buuuuut...)

**Comment by fippo** [comment]
*sigh*... wrong button :-(
squashed and rewrote history.
