### PR TITLE
common: make URL.createObjectURL shim depend on native support

### LINKED ISSUE #569: Conflict with external JS librairies
**Browsers and versions affected**
Tested on Chrome with latest adapter.js

**Description**
When deploying adapter.js on customer site, it happen that there is conflicts between existing JS librairies on the web site and adapter.js
I have two example with requireJs and browser.js

**Steps to reproduce**
I have prepared some simple page to show the issues :

Issue 1 :
http://www.apizee.com/Demo/testAdapter/testAdapterRequireJS.html
Error : Uncaught Error: Mismatched anonymous define() module: function (){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function" [...]

Issue 2 : http://www.apizee.com/Demo/testAdapter/testAdapterBrowser.html
Error : Uncaught TypeError: Cannot read property 'bind' of undefined
    at Object.shimCreateObjectURL (adapter-latest.js:3445)
    at adapter-latest.js:657 [...]

**Expected results**
Would expect adapter.js to have no conflict / impact with other librairies

**Actual results**
Conflict cause that adapter.js script cannot be executed

### PR DESCRIPTION
**Pull request by fippo**
fixes #569

### CODE REVIEW

File: src/js/utils.js [hunk 1]
```diff
@@ -145,6 +145,9 @@ var utils = {
 
     var nativeCreateObjectURL = URL.createObjectURL.bind(URL);
     var nativeRevokeObjectURL = URL.revokeObjectURL.bind(URL);
```
Comment (jan-ivar) [inline src/js/utils.js]: This still calls `undefined.bind()`. Better to test for 
```js
if (!URL.createObjectURL || !URL.revokeObjectURL)
```

**Review by jan-ivar — CHANGES_REQUESTED** [review]

File: src/js/utils.js (hunk 1 above)
Comment (fippo) [reply src/js/utils.js]: moved up a bit, thanks for suggesting this!

**Review by KaptenJansson — APPROVED** [review]
