### PR TITLE
chrome_shim: reject removeTrack(track)

### LINKED ISSUE #624: removeTrack fails with 'Sender was not created by this connection.'
**Browsers and versions affected**
Chrome: Version 59.0.3071.115 (Official Build) (64-bit)
adapter.js: 4.2.0

**Description**
Calling removeTrack causes the exception 'Sender was not created by this connection.'.
The code that's failing is: 
      var isLocal = sender._pc === pc;
      if (!isLocal) {
        throw new DOMException('Sender was not created by this connection.',
            'InvalidAccessError');
      }

sender._pc is undefined. The only place _pc appears to be set is in the routine shimGetSendersWithDtmf.

**Steps to reproduce**
Call removeTrack

**Expected results**
Track should be removed without throwing an exception

**Actual results**
An exception is thrown.

### PR DESCRIPTION
**Pull request by fippo**
rejects removeTrack(track) explicitly, fixes #624.

### CODE REVIEW

File: test/e2e/expectations/MicrosoftEdge [hunk 1]
```diff
@@ -35,6 +35,7 @@ PASS track event the event has a track
 PASS track event the event has a set of streams
 PASS track event the event has a receiver that is contained in the set of receivers
 ERR removeTrack allows removeTrack twice timeout
+ERR removeTrack throws an exception if the argument is a track, not a sender AssertionError
```
Comment (fippo) [inline test/e2e/expectations/MicrosoftEdge:38]: I learned to cheat by using vs code :-)

File: src/js/chrome/chrome_shim.js [hunk 2]
```diff
@@ -338,6 +338,12 @@ var chromeShim = {
           'The RTCPeerConnection\'s signalingState is \'closed\'.',
           'InvalidStateError');
       }
+      // We can not yet check for sender instanceOf RTCRtpSender
```
Comment (jan-ivar) [inline src/js/chrome/chrome_shim.js]: instanceof

**Review by jan-ivar — APPROVED** [review]

**Review by KaptenJansson — APPROVED** [review]
