### PR TITLE
Fail silently if unable to shim GetUserMedia & AddTrackRemoveTrack & PeerConnection on chrome

### LINKED ISSUE #895: Script should silently fail if `RTCPeerConnection` is undefined
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected

Browser: **Google Crawler**
**webrtc-adapter 6.4.3**

## Description

Google crawler uses some special version of Chrome to crawl pages and it has no `RTCPeerConnection` support. That leads to google crawler seeing blank pages for SPA because of a JS error.

## Steps to reproduce

1. Import `webrtc-adapter` somewhere in any SPA (e.g create-react-app) so it's all bundled in a single file
2. Use https://search.google.com/test/mobile-friendly to see that it fails with `Uncaught TypeError: Cannot read property 'prototype' of undefined` that happens on `RTCPeerConnection.prototype`

## Expected results

Google crawler can render the page

## Actual results

Google crawler can not render the page

### PR DESCRIPTION
**Pull request by mariuszbeltowski**
**Description**
Fail silently if unable to shim GetUserMedia & AddTrackRemoveTrack & PeerConnection on chrome

**Purpose**
Fixed #895

### CODE REVIEW

File: src/js/chrome/getusermedia.js [hunk 1]
```diff
@@ -11,9 +11,14 @@ import * as utils from '../utils.js';
 const logging = utils.log;
 
 export function shimGetUserMedia(window) {
-  const browserDetails = utils.detectBrowser(window);
   const navigator = window && window.navigator;
 
+  if (!navigator.mediaDevices) {
```
Comment (fippo) [inline src/js/chrome/getusermedia.js:16]: I think this needs to be if (!(navigator && navigator.mediaDevices)) to be perfectly safe.

File: src/js/chrome/chrome_shim.js [hunk 2]
```diff
@@ -403,6 +403,9 @@ export function shimAddTrackRemoveTrackWithNative(window) {
 }
 
 export function shimAddTrackRemoveTrack(window) {
+  if (!window.RTCPeerConnection) {
```
Comment (fippo) [inline src/js/chrome/chrome_shim.js:406]: I wondered if this is needed in shimAddTrackRemoveTrackWithNative too but it isn't because that path is going through this function.

**Comment by fippo** [comment]
LGTM overall, thank you!
I considered doing this in adapter_factory but this is better. Small suggestion, I can merge without.
Will take care of backporting it to the 6.x tree.

File: src/js/chrome/getusermedia.js (hunk 1 above)
Comment (mariuszbeltowski) [reply src/js/chrome/getusermedia.js:16]: To be perfectly safe, we should also protect the other browser shims, but I didn't see the point. This was tested on the Google Crawler as the issue described, where the `navigator` is present. I can add the additional check suggested by you if you prefer :)

Comment (fippo) [reply src/js/chrome/getusermedia.js:16]: nah, without navigator this will probably blow up in many other places

**Comment by fippo** [comment]
(will merge in the evening)

File: src/js/chrome/getusermedia.js (hunk 1 above)
Comment (fippo) [reply src/js/chrome/getusermedia.js:16]: to answer my own question: as long as this is used from adapter_core, navigator will always be defined.

Comment (mariuszbeltowski) [reply src/js/chrome/getusermedia.js:16]: I will better add some unit tests, to prevent the issue appear again

**Comment by mariuszbeltowski** [comment]
In the meantime, I've added unit tests to cover this issue

**Review by fippo — APPROVED** [review]
I very much approve more tests!

**Comment by fippo** [comment]
can you take a look at https://github.com/webrtcHacks/adapter/tree/backport-6.4.7 please? I just took the RTCPeerConnection things because the getUserMedia stuff there because it only assume webkitGetUserMedia exists which is covered by the outside code in adapter_factory
