### PR TITLE
chrome: munge sdp to keep stream ids

### LINKED ISSUE #634: Chrome: MSID does not match MediaStream passed to addStream or addTrack
**Browsers and versions affected**

Google Chrome 59, 60

**Description**

adapter.js appears to be changing MSID values when `addStream` or `addTrack` is used.

**Steps to reproduce**

* [JSFiddle using `addStream` without adapter.js](https://jsfiddle.net/7sh3oc28/) (Chrome, Firefox)
* [JSFiddle using `addStream` with adapter.js (latest)](https://jsfiddle.net/cs22nvjL/) (Chrome, Firefox)
* [JSFiddle using `addTrack` without adapter.js](https://jsfiddle.net/3e2t3wzv/1/) (Firefox)
* [JSFiddle using `addTrack` with adapter.js (latest)](https://jsfiddle.net/1nbr1u7m/1/) (Chrome, Firefox)

**Expected results**

I get these expected results when adapter.js is not used in both Chrome and Firefox.

```
stream.id $STREAM_ID
track.id $TRACK_ID
$OFFER
msid $STREAM_ID $TRACK_ID
stream.id === msid[0] true
track.id === msid[1] true
```

**Actual results**

I get these results when adapter.js is used in Chrome.

```
stream.id $STREAM_ID
track.id $TRACK_ID
$OFFER
msid $RANDOM_ID $TRACK_ID
stream.id === msid[0] false
track.id === msid[1] true
```

### PR DESCRIPTION
**Pull request by fippo**
munges the SDP in createOffer, createAnswer and setLocalDescription as well
as the pc.localDescription accessor in order to retain the stream ids that
are modifed by the addTrack shim.

Fixes #634 

@henbos can you take a look? I tried to mangle the getStats result too but that didn't work :-/

### CODE REVIEW

**Comment by henbos** [comment]
Shimming getStats didn't work? Isn't the only thing that needs to be updated RTCMediaStreamStats.streamIdentifiers and RTCMediaStreamTrackStats.trackIdentifier?

**Comment by fippo** [comment]
tracks are kept the same ;-)
I had a patch that did this:
```
-    // TODO: mangle getStats: https://w3c.github.io/webrtc-stats/#dom-rtcmediastreamstats-streamidentifier
+    var origGetStats = window.RTCPeerConnection.prototype.getStats;
+    window.RTCPeerConnection.prototype.getStats = function() {
+      var pc = this;
+      return origGetStats.apply(pc, arguments)
+      .then(function(result) {
+        result.forEach(function(stat) {
+          if (stat.type === 'stream' && pc._reverseStreams) {
+            var externalStream = pc._reverseStreams[stat.streamIdentifier];
+            if (externalStream) {
+              stat.streamIdentifier = externalStream.id;
+            }
+          }
+        });
+        return result;
+      });
+    };
```
It seemed to work but magically in the next function the streamIdentifier was the old string again.

**Comment by henbos** [comment]
Maybe another shimming of getStats overwrites that shimming?

**Comment by fippo** [comment]
nah, I iterated again with another forEach before the "return result". Check here:
    https://jsfiddle.net/jfoe1L7g/
Really really odd...

**Comment by henbos** [comment]
Oh, the stats objects are dictionaries, so they are returned as copies. Once returned you can modify them, but because the RTCStatsReport is a Maplike interface, every time you retrieve an element you get a copy of the original. In order to mangle this you need to mangle `result`. I think `Map` is a `Maplike`? If so you can just add all the modified members to a `new Map()` and return that.

**Comment by henbos** [comment]
https://jsfiddle.net/s9goLhbp/1/

**Comment by markandrus** [comment]
Any ETA/pre-reqs for landing this? The only workaround I could see was pulling copies of `addStream` and `removeStream` off a "fresh" RTCPeerConnection `prototype` from an &lt;iframe&gt;, but I really don't want to land such a workaround in my code...

**Comment by KaptenJansson** [comment]
@henbos could you take a look at the latest commit?

**Comment by fippo** [comment]
track-based test failures in beta with experimental flag is real now... @henbos we need to have a fig.. err friendly chat ;-)

**Comment by fippo** [comment]
@jan-ivar can you take a look at https://github.com/webrtc/adapter/pull/637/commits/466e3f651d306dbb59734421887eba99920f2396 please? I noticed that createOffer(cb, err, opts) resolved the promise with no arguments which lead to a very very confusing error.

**Comment by jan-ivar** [comment]
@fippo I'd say leave legacy code alone, so we A) don't break it and B) leave the pearls for migraters.

The legacy callback methods return `Promise<void>` [per spec](https://w3c.github.io/webrtc-pc/#legacy-interface-extensions) due to webidl overloading limitations.

File: src/js/chrome/chrome_shim.js [hunk 1]
```diff
@@ -335,6 +335,82 @@ var chromeShim = {
...
+      window.RTCPeerConnection.prototype[method] = function() {
+        var pc = this;
+        var opts;
+        var args = arguments;
+        if (arguments.length === 1 && typeof arguments[0] === 'object') {
+          opts = arguments[0];
+        } else if (arguments.length === 3 && typeof arguments[2] === 'object') {
+          opts = arguments[2];
+        }
+        return nativeMethod.apply(pc, [opts])
```
Comment (jan-ivar) [inline src/js/chrome/chrome_shim.js]: So this diverts calls of the legacy callback API to the promise API, which I don't like, as it will suppress native deprecation warnings (like in Firefox), and may also skew any telemetry of how many still call the legacy API. How about:
```js
var p, isLegacyCall = arguments.length && typeof arguments[0] === 'function';
if (isLegacyCall) {
  p = new Promise((r, e) => nativeMethod.apply(pc, [r, e, arguments[2]]));
} else {
  p = nativeMethod.apply(pc, arguments);
}
```
?

File: src/js/chrome/chrome_shim.js [hunk 2]
```diff
@@ -335,6 +335,82 @@ var chromeShim = {
...
+          var desc = new window.RTCSessionDescription({
+            type: description.type,
+            sdp: sdp
+          });
+          if (args.length > 0 && typeof args[0] === 'function') {
+            args[0].apply(null, [desc]);
+            return Promise.resolve();
+          }
+          return desc;
+        }, function(err) {
```
Comment (jan-ivar) [inline src/js/chrome/chrome_shim.js]: You're not catching any potential programming errors in this code. I'd change `.then(a, b)` to `.then(a).catch(b)`.

File: src/js/chrome/chrome_shim.js [hunk 3]
```diff
@@ -335,6 +335,82 @@ var chromeShim = {
...
+            sdp = sdp.replace(new RegExp(internalStream.id, 'g'),
+                externalStream.id);
+          });
+          var desc = new window.RTCSessionDescription({
+            type: description.type,
+            sdp: sdp
+          });
+          if (args.length > 0 && typeof args[0] === 'function') {
+            args[0].apply(null, [desc]);
+            return Promise.resolve();
```
Comment (jan-ivar) [inline src/js/chrome/chrome_shim.js]: redundant. Just `return;` will do

File: src/js/chrome/chrome_shim.js [hunk 4]
```diff
@@ -335,6 +335,82 @@ var chromeShim = {
...
+          }
+          return desc;
+        }, function(err) {
+          if (args.length > 1 && typeof args[1] === 'function') {
+            args[1].apply(null, [err]);
+          }
```
Comment (jan-ivar) [inline src/js/chrome/chrome_shim.js]: `} else { throw err; }` otherwise you're removing errors for promise-users.

**Review by jan-ivar — CHANGES_REQUESTED** [review]

File: src/js/chrome/chrome_shim.js [hunk 5]
```diff
@@ -337,34 +337,54 @@ var chromeShim = {
...
           var sdp = description.sdp;
-          Object.keys(pc._reverseStreams || []).forEach(function(internalId) {
-            var externalStream = pc._reverseStreams[internalId];
-            var internalStream = pc._streams[externalStream.id];
-            sdp = sdp.replace(new RegExp(internalStream.id, 'g'),
-                externalStream.id);
-          });
           var desc = new window.RTCSessionDescription({
             type: description.type,
             sdp: sdp
```
Comment (jan-ivar) [inline src/js/chrome/chrome_shim.js]: I think you meant to call `replaceInternalStreamId()` here.

File: src/js/chrome/chrome_shim.js [hunk 6]
```diff
@@ -378,30 +398,17 @@ var chromeShim = {
...
-      .then(function() {
-        if (args.length > 1 && typeof args[1] === 'function') {
-          args[1].apply(null, []);
-        }
-      })
-      .catch(function(err) {
-        if (args.length > 2 && typeof args[2] === 'function') {
-          args[2].apply(null, [err]);
-        }
+        sdp: replaceExternalStreamId(pc, arguments[0].sdp)
```
Comment (jan-ivar) [inline src/js/chrome/chrome_shim.js]: We might want to wrap this in
```js
if (arguments[0].type || typeof arguments[0].sdp === 'string')
```
to protect this polyfill from bogus input without having to mimic native error checking.

**Review by jan-ivar — CHANGES_REQUESTED** [review]

File: src/js/chrome/chrome_shim.js (hunk 5 above)
Comment (fippo) [reply src/js/chrome/chrome_shim.js]: no, we take the external stream id in the SDP (which comes from createOffer/createAnswer usually) and replace it with the internal one before SLD. I agree that the naming is suboptimal, but its two different operations

File: src/js/chrome/chrome_shim.js (hunk 6 above)
Comment (fippo) [reply src/js/chrome/chrome_shim.js]: 👍 -- I didn't check for .sdp because rollbacks

**Comment by KaptenJansson** [comment]
@henbos could you take another look?

File: src/js/chrome/chrome_shim.js [hunk 7]
```diff
@@ -335,6 +335,97 @@ var chromeShim = {
...
+      var desc = new window.RTCSessionDescription({
+        type: arguments[0].type,
+        sdp: replaceExternalStreamId(pc, arguments[0].sdp)
+      });
+      var isLegacyCall = arguments.length > 1;
+      if (isLegacyCall) {
+        return origSetLocalDescription.apply(pc,
+            [desc, arguments[1], arguments[2]]);
+      }
+      return origSetLocalDescription.apply(pc, [desc]);
```
Comment (henbos) [inline src/js/chrome/chrome_shim.js]: Can you instead of "var desc = ..." do "arguments[0] = ..." and then do "origSetLocalDescription.apply(pc, arguments)" and get rid of the isLegacyCall check?

File: src/js/chrome/chrome_shim.js [hunk 8]
```diff
@@ -335,6 +335,97 @@ var chromeShim = {
...
+        sdp = sdp.replace(new RegExp(externalStream.id, 'g'),
+            internalStream.id);
+      });
+      return sdp;
+    }
+    ['createOffer', 'createAnswer'].forEach(function(method) {
+      var nativeMethod = window.RTCPeerConnection.prototype[method];
+      window.RTCPeerConnection.prototype[method] = function() {
+        var pc = this;
+        var args = arguments;
```
Comment (henbos) [inline src/js/chrome/chrome_shim.js:372]: No need for "args", simply use "arguments".

File: src/js/chrome/chrome_shim.js [hunk 9]
```diff
@@ -335,6 +335,97 @@ var chromeShim = {
...
+    }
+    function replaceExternalStreamId(pc, sdp) {
+      Object.keys(pc._reverseStreams || []).forEach(function(internalId) {
+        var externalStream = pc._reverseStreams[internalId];
+        var internalStream = pc._streams[externalStream.id];
+        sdp = sdp.replace(new RegExp(externalStream.id, 'g'),
+            internalStream.id);
+      });
+      return sdp;
+    }
```
Comment (henbos) [inline src/js/chrome/chrome_shim.js]: Every call to replaceInternal/ExternalStreamId is in a "new window.RTCSessionDescription". If you make these functions do that bit too you reduce a few repeated lines of code in the rest of the file.

File: src/js/chrome/chrome_shim.js [hunk 10]
```diff
@@ -335,6 +335,97 @@ var chromeShim = {
...
+      });
+      var isLegacyCall = arguments.length > 1;
+      if (isLegacyCall) {
+        return origSetLocalDescription.apply(pc,
+            [desc, arguments[1], arguments[2]]);
+      }
+      return origSetLocalDescription.apply(pc, [desc]);
+    };
+
+    // TODO: mangle getStats: https://w3c.github.io/webrtc-stats/#dom-rtcmediastreamstats-streamidentifier
```
Comment (henbos) [inline src/js/chrome/chrome_shim.js]: Do you want to do this separately? https://jsfiddle.net/s9goLhbp/1/

File: test/e2e/msid.js [hunk 11]
```diff
@@ -0,0 +1,56 @@
...
+      expect(e.streams[0].id).to.equal(localStream.id);
+      done();
+    };
+    navigator.mediaDevices.getUserMedia({video: true})
+    .then((stream) => {
+      localStream = stream;
+      pc1.addTrack(stream.getTracks()[0], stream);
+      return negotiate(pc1, pc2);
+    });
+  });
```
Comment (henbos) [inline test/e2e/msid.js:55]: Add a test that verifies "localDescription" is what you expect.

**Review by henbos — CHANGES_REQUESTED** [review]
Looking good.

File: src/js/chrome/chrome_shim.js (hunk 8 above)
Comment (fippo) [reply src/js/chrome/chrome_shim.js:372]: no, args is used in the legacy case. Can't use arguments there since that is a different function scope

File: src/js/chrome/chrome_shim.js (hunk 7 above)
Comment (fippo) [reply src/js/chrome/chrome_shim.js]: sneaky...

File: src/js/chrome/chrome_shim.js (hunk 10 above)
Comment (fippo) [reply src/js/chrome/chrome_shim.js]: yeah, different PR

File: test/e2e/msid.js (hunk 11 above)
Comment (fippo) [reply test/e2e/msid.js:55]: A test for accessing .localDescription is indeed missing. Can I add this later? I promise ;-)

File: src/js/chrome/chrome_shim.js (hunk 8 above)
Comment (henbos) [reply src/js/chrome/chrome_shim.js:372]: Acknowledged.

File: test/e2e/msid.js (hunk 11 above)
Comment (henbos) [reply test/e2e/msid.js:55]: If so can you create a bug or add a TODO?

**Review by henbos — APPROVED** [review]
LGTM

**Review by KaptenJansson — APPROVED** [review]
