### PR TITLE
Firefox ignores addTransceiver init setEncodings opts

### LINKED ISSUE #998: addTransceiver Firefox ignores init options
##  Description
It seems to me that the addTransceiver function in Firefox is ignoring the sendEncodings parameter during initialization.

As per doc: [MDN](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTransceiver) the constructor takes in input an init object which can contains the sendEncodings options.

When passing this object to Chrome, everything's fine
When passing this object to Firefox, it gets ignored. The only way to apply these parameters, is getting the sender configuration, re-add the sendEncodings parameters and set again the options into the sender.

This last step, however, is not very appreciated by Chrome which complaints about the fact that we are re-setting the rids which are now read only.

This was stated clearly  in this PSA [Spec-compliant Simulcast using addTransceiver API](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/discuss-webrtc/32Y1AUzQ9XU/rfzss0SQAgAJ)

> The simulcast envelope (i.e. the number of layers and their RIDs) cannot be changed and is determined in the call to addTransceiver().
> After the number of layers is determined, the RtpSenderInterface can be queried for the parameters using getParameters()
> and the configuration for layers (not their number or RIDs) can change using setParameters().

I suspect this is a Firefox bug, and if so, adapter can shim the addTransceiver function (only in Firefox) and re-apply the init parameters so we don't have to manage the different cases in our client logic.

Also, if you think this is a bug and not mine misunderstanding, I'll proceed to file a bug issue.

## Steps to reproduce
discalimer: Not an html/css developer here so please be gentle with my example page. Also note that I reused a "playground" page with lots of other things but you can find the culprit on JS line 179.

Chrome 75.0.3770.100, FF 68.0.1

[LINK TO EXAMPLE CODEPEN](https://codepen.io/anon/pen/jgBdzx)

Click get media
Click Create PeerConnection
Click Create Offer
Observe Generated offer

If you change the line 179 in if (true), then Firefox works but chrome complaints

What do you think @fippo? Am I missing something?
thanks

### PR DESCRIPTION
**Pull request by kekkokk**
should fix https://github.com/webrtcHacks/adapter/issues/998

### CODE REVIEW

File: src/js/firefox/firefox_shim.js [hunk 1]
```diff
@@ -190,3 +190,79 @@ export function shimRTCDataChannel(window) {
...
+  const origAddTransceiver = window.RTCPeerConnection.prototype.addTransceiver;
+  if (origAddTransceiver) {
+    window.RTCPeerConnection.prototype.addTransceiver =
+      function addTransceiver() {
+        const initParameters = arguments[1];
+        const shouldPerformCheck = initParameters &&
+                                  'sendEncodings' in initParameters;
+        if (shouldPerformCheck) {
+          // If sendEncodings params are provided, validate grammar
+          initParameters.sendEncodings.forEach((encodgingParam) => {
```
Comment (jan-ivar) [inline src/js/firefox/firefox_shim.js]: Typo. `s/encodgingParam/encodingParam/`

File: src/js/firefox/firefox_shim.js [hunk 2]
```diff
@@ -190,3 +190,79 @@ export function shimRTCDataChannel(window) {
...
+          // Also note that after the createoffer we are not 100% sure that
+          // the params were asynchronously applied so we might miss the
+          // opportunity to recreate offer.
+          const sender = transceiver.sender;
+          if (sender) {
+            const params = sender.getParameters();
+            if (!('encodings' in params)) {
+              setParametersPromises.push(
+                sender.setParameters({encodings: initParameters.sendEncodings})
+                .catch(() => Promise.resolve())
```
Comment (jan-ivar) [inline src/js/firefox/firefox_shim.js]: Nit: `.catch(() => {})` implicitly converts to a promise, so create one is redundant.

File: src/js/firefox/firefox_shim.js [hunk 3]
```diff
@@ -190,3 +190,79 @@ export function shimRTCDataChannel(window) {
...
+        if (shouldPerformCheck) {
+          // Check if the init options were applied. If not we do this in an
+          // asynchronous way and save the promise reference in a global object.
+          // This is an ugly hack, but at the same time is way more robust than
+          // checking the sender parameters before and after the createOffer
+          // Also note that after the createoffer we are not 100% sure that
+          // the params were asynchronously applied so we might miss the
+          // opportunity to recreate offer.
+          const sender = transceiver.sender;
+          if (sender) {
```
Comment (jan-ivar) [inline src/js/firefox/firefox_shim.js]: Nit: redundant `if`. All transceivers have a sender.

File: src/js/firefox/firefox_shim.js [hunk 4]
```diff
@@ -190,3 +190,79 @@ export function shimRTCDataChannel(window) {
...
+}
+
+export function shimCreateOffer(window) {
+  // https://github.com/webrtcHacks/adapter/issues/998#issuecomment-516921647
+  // Firefox ignores the init sendEncodings options passed to addTransceiver
+  // https://bugzilla.mozilla.org/show_bug.cgi?id=1396918
+  const origCreateOffer = window.RTCPeerConnection.prototype.createOffer;
+  if (origCreateOffer) {
+    window.RTCPeerConnection.prototype.createOffer = function createOffer() {
+      return Promise.all(setParametersPromises)
```
Comment (jan-ivar) [inline src/js/firefox/firefox_shim.js]: Looks good, except I think I'd prefer to add the following lines directly ahead of the above line:
```js
if (!setParametersPromises.length) {
  return origCreateOffer.apply(this, arguments);
}
```
That way we only disturb the timing of *createOffer*'s synchronous validation steps when necessary (mostly an [[IsClosed]] test). It's really only observable in the JS debugger (Promise appears \<rejected> in console immediately), but still.

It'd make me feel better if we didn't disturb the timing of *every* createOffer out there.

**Review by jan-ivar — APPROVED** [review]
Awesome, thanks!

**Comment by jan-ivar** [comment]
I guess *technically* we'd want to do this in *createAnswer* too?

File: src/js/firefox/firefox_shim.js [hunk 5]
```diff
@@ -190,3 +190,79 @@ export function shimRTCDataChannel(window) {
     window.RTCDataChannel = window.DataChannel;
   }
 }
+
+let setParametersPromises = [];
+export function shimAddTransceiver(window) {
+  // https://github.com/webrtcHacks/adapter/issues/998#issuecomment-516921647
```
Comment (fippo) [inline src/js/firefox/firefox_shim.js:195]: what the test caught here is a missing
```
  if (!(typeof window === 'object' && window.RTCPeerConnection)) {
    return;
  }
```

File: src/js/firefox/firefox_shim.js (hunk 3 above)
Comment (fippo) [reply src/js/firefox/firefox_shim.js]: also: const {sender} = transceiver;

File: src/js/firefox/firefox_shim.js [hunk 6]
```diff
@@ -190,3 +190,79 @@ export function shimRTCDataChannel(window) {
...
+          // checking the sender parameters before and after the createOffer
+          // Also note that after the createoffer we are not 100% sure that
+          // the params were asynchronously applied so we might miss the
+          // opportunity to recreate offer.
+          const sender = transceiver.sender;
+          if (sender) {
+            const params = sender.getParameters();
+            if (!('encodings' in params)) {
+              setParametersPromises.push(
+                sender.setParameters({encodings: initParameters.sendEncodings})
```
Comment (fippo) [inline src/js/firefox/firefox_shim.js]: you need to set params.encodings and then call setParameters. setParameters should reject but doesn't in Firefox.
Do we need more here like maxBitrate?

File: src/js/firefox/firefox_shim.js [hunk 7]
```diff
@@ -190,3 +190,79 @@ export function shimRTCDataChannel(window) {
...
+      };
+  }
+}
+
+export function shimCreateOffer(window) {
+  // https://github.com/webrtcHacks/adapter/issues/998#issuecomment-516921647
+  // Firefox ignores the init sendEncodings options passed to addTransceiver
+  // https://bugzilla.mozilla.org/show_bug.cgi?id=1396918
+  const origCreateOffer = window.RTCPeerConnection.prototype.createOffer;
+  if (origCreateOffer) {
```
Comment (fippo) [inline src/js/firefox/firefox_shim.js]: if you add the same "does RTCPeerConnection exist" check  as above  you can skip this check

File: src/js/firefox/firefox_shim.js [hunk 8]
```diff
@@ -190,3 +190,79 @@ export function shimRTCDataChannel(window) {
     window.RTCDataChannel = window.DataChannel;
   }
 }
+
+let setParametersPromises = [];
```
Comment (fippo) [inline src/js/firefox/firefox_shim.js]: doesn't this need to be per peerconnection, i.e. pc._setParametersPromises? Otherwise we create dependencies between peerconnections

**Comment by kekkokk** [comment]
Thanks guys for the suggestions. I reviewed all your points with my colleague @simonemazzoni
I also implemented it for the createanswer but I wasn't really able to test so any help would be appreciated.

File: src/js/firefox/firefox_shim.js (hunk 6 above)
Comment (kekkokk) [reply src/js/firefox/firefox_shim.js]: need some info from @jan-ivar for this topic

File: src/js/firefox/firefox_shim.js (hunk 8 above)
Comment (kekkokk) [reply src/js/firefox/firefox_shim.js]: Totally right, I did not think about it and I thought that was not a nice thing to "inject" parameters in the PeerConnection if possible. But in this case I think is the only solution

**Comment by fippo** [comment]
I wonder if we should have a e2e test along the lines of:
1) call pc.addTransceiver with a video track and sendEncodings
2) call pc.createOffer()
3) check that the offer contains an a=simulcast line.

We would need to make testable in Chrome too since that is how the e2e tests work... but Chrome generates different SDP (slightly)

**Comment by kekkokk** [comment]
Tried to implement a basic e2e test, never did this so be patient. Feel free to rewrite from scratch
thanks @fippo 

ps. I created a new simulcast.js in which we can also add the e2e test for enabling simulcast via sdp munging

File: test/e2e/simulcast.js [hunk 9]
```diff
@@ -0,0 +1,51 @@
...
+    pc1 = new RTCPeerConnection(null);
+  });
+  afterEach(() => {
+    pc1.close();
+  });
+
+  it('using transceivers APIs', (done) => {
+    if (window.adapter.browserDetails.browser === 'edge' ||
+      window.adapter.browserDetails.browser === 'safari') {
+      this.skip();
```
Comment (fippo) [inline test/e2e/simulcast.js:24]: this isn't defined in arrow functions (the general recommendation is not to use arrow functions but...) so you'll need to make the it a regular function.

File: test/e2e/simulcast.js [hunk 10]
```diff
@@ -0,0 +1,51 @@
...
+    }
+    var constraints = {video: true};
```
Comment (fippo) [inline test/e2e/simulcast.js]: const

File: test/e2e/simulcast.js [hunk 11]
```diff
@@ -0,0 +1,51 @@
...
+    navigator.mediaDevices.getUserMedia(constraints)
+      .then(function(stream) {
+        const initOpts = {
+          sendEncodings: [
+            {'rid': 'high'},
```
Comment (fippo) [inline test/e2e/simulcast.js]: {rid: 'high'} et al

File: test/e2e/simulcast.js [hunk 12]
```diff
@@ -0,0 +1,51 @@
...
+  });
+
+  it('using transceivers APIs', (done) => {
+    if (window.adapter.browserDetails.browser === 'edge' ||
+      window.adapter.browserDetails.browser === 'safari') {
+      this.skip();
+    }
+    var constraints = {video: true};
+    navigator.mediaDevices.getUserMedia(constraints)
+      .then(function(stream) {
```
Comment (fippo) [inline test/e2e/simulcast.js]: arrow function please

File: test/e2e/simulcast.js [hunk 13]
```diff
@@ -0,0 +1,51 @@
...
+        const initOpts = {
+          sendEncodings: [
+            {'rid': 'high'},
+            {'rid': 'medium', 'scaleResolutionDownBy': 2},
+            {'rid': 'low', 'scaleResolutionDownBy': 3}
```
Comment (fippo) [inline test/e2e/simulcast.js]: i think you need 4 here?

File: test/e2e/simulcast.js [hunk 14]
```diff
@@ -0,0 +1,51 @@
...
+        pc1.addTransceiver(stream.getVideoTracks()[0], initOpts);
+
+        pc1.createOffer().then((offer) => {
+          const simulcastRegex = /a=simulcast:.*send .*high;medium;low/g;
+          expect(simulcastRegex.test(offer.sdp)).to.equal(true);
+          done();
+        })
+        .catch(throwError);
+      })
+      .catch(throwError);
```
Comment (fippo) [inline test/e2e/simulcast.js]: I think instead of the done-throwError you can return a promise chain from GUM to createOffer and the result of this last check

File: src/js/firefox/firefox_shim.js (hunk 6 above)
Comment (jan-ivar) [reply src/js/firefox/firefox_shim.js]: Yeah that line deviated from what I suggested in https://github.com/webrtcHacks/adapter/issues/998#issuecomment-516921647 but I didn't flag it, because this code would only ever run in a Firefox without a proper *setParameters* implementation, so it seemed fine. 

That said, @fippo is right the following would be more correct (avoids suppressing other init options outside of encodings for no reason—Firefox just doesn't support any of them atm):
```js
setParameters(Object.assign({}, init, {encodings: initParameters.sendEncodings}))
```

`maxBitrate` is already part of [RTCRtpEncodingParameters](https://w3c.github.io/webrtc-pc/#dom-rtcrtpencodingparameters) so we should be good there.

File: src/js/firefox/firefox_shim.js (hunk 8 above)
Comment (jan-ivar) [reply src/js/firefox/firefox_shim.js]: Good catch! I missed that.

Comment (jan-ivar) [reply src/js/firefox/firefox_shim.js]: > I thought that was not a nice thing to "inject" parameters in the PeerConnection if possible

Could we maybe modify the patch to create it on-demand, i.e. only if `sendEncodings` is actually used?

File: test/e2e/simulcast.js (hunk 13 above)
Comment (kekkokk) [reply test/e2e/simulcast.js]: Seems that setting to 4 breaks chrome 77 dev.
Did we found a bug? XD

I tried to also make a GUM in 1080p but it gives me only the first 3 layers in 77 dev.

Comment (kekkokk) [reply test/e2e/simulcast.js]: seems that Webrtc is switching from a max of 4 to a max of 3 in m77

[m75](https://chromium.googlesource.com/external/webrtc/+/branch-heads/m75/api/video/video_codec_constants.h)

[m77](https://chromium.googlesource.com/external/webrtc/+/branch-heads/m77/api/video/video_codec_constants.h)

so... idk. I revert the tests from 4 to 3?

File: test/e2e/simulcast.js [hunk 15]
```diff
@@ -0,0 +1,46 @@
...
+        pc1.addTransceiver(stream.getVideoTracks()[0], initOpts);
+
+        return pc1.createOffer().then((offer) => {
+          const simulcastRegex =
+          /a=simulcast:[\s]?send (?:rid=)?original;high;medium;low/g;
+          return expect(simulcastRegex.test(offer.sdp)).to.equal(true);
+        });
+      });
+  });
+});
```
Comment (jan-ivar) [inline test/e2e/simulcast.js]: Add newline.

**Review by jan-ivar — APPROVED** [review]
This looks great! Did it stall?

**Comment by fippo** [comment]
no, now its blocked by chrome canary failing for some reason. Arguably that is unrelated to Firefox so...

**Comment by kekkokk** [comment]
Yeah seems that new webrtc codebase does not accept more than 3 layers, so it fails on canary. 
https://github.com/webrtcHacks/adapter/pull/1004#discussion_r310560149

How do we proceed?

**Comment by fippo** [comment]
yeah, lets go for 3 layers and 2/4 scaledown

@orphis: you might want to check the above is intended if anyone uses this.

File: test/e2e/simulcast.js (hunk 13 above)
Comment (Orphis) [reply test/e2e/simulcast.js]: We're not really switching, the 4th layer would never be used because of some internal limiting of simulcast layer count. Trying to remove that limitation showed that the 4th one was unusable for other reasons, so we properly limit it to 3 now (until we fix the other issue).

File: test/e2e/simulcast.js [hunk 16]
```diff
@@ -0,0 +1,46 @@
...
+    }
+    const constraints = {video: true};
+    return navigator.mediaDevices.getUserMedia(constraints)
+      .then((stream) => {
+        const initOpts = {
+          sendEncodings: [
+            {rid: 'original'},
+            {rid: 'high', scaleResolutionDownBy: 2},
+            {rid: 'medium', scaleResolutionDownBy: 3},
+            {rid: 'low', scaleResolutionDownBy: 4}
```
Comment (Orphis) [inline test/e2e/simulcast.js:33]: libwebrtc doesn't support more than 3 simulcast layers, and so does Chrome. You should probably reduce the layer count here.

**Review by Orphis — CHANGES_REQUESTED** [review]
You should only use 3 simulcast layers in your test at most.

**Comment by fippo** [comment]
>           /a=simulcast:[\s]?send (?:rid=)?original;high;medium;low/g;
One last thing to push it over the finish line :-)

**Comment by kekkokk** [comment]
> > ```
> >       /a=simulcast:[\s]?send (?:rid=)?original;high;medium;low/g;
> > ```
> 
> One last thing to push it over the finish line :-)

ooops, I'm on vacation and I'm totally not focused XD

**Comment by fippo** [comment]
will publish 7.3.0 soonish. Enjoy your vacation!
